Lesson03/Models/Assignment.cs
namespace Lesson03.Models
{
    public class Assignment
    {
        public int Id { get; set; }

        public int TeacherId { get; set; }
        public Teacher Teacher { get; set; }
        public int SubjectId { get; set; }
        public Subject Subject { get; set; }
    }
}

Lesson03/Controllers/AssignmentsController.cs
using Lesson03.DAL;
using Lesson03.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Lesson03.Controllers
{
    public class AssignmentsController : Controller
    {
        private readonly PdpDbContext _context;

        public AssignmentsController(PdpDbContext context)
        {
            _context = context;
        }

        // GET: Assignments
        public async Task<IActionResult> Index()
        {
            var pdpDbContext = _context.Assignments.Include(a => a.Subject).Include(a => a.Teacher);
            return View(await pdpDbContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(int SearchId)
        {
            var assignments = _context.Assignments.AsQueryable();
            if (!AssignmentExists(SearchId))
            {
                assignments = assignments
                    .Include(a => a.Teacher)
                    .Include(a => a.Subject);
                return View(await assignments.ToListAsync());
            }
            assignments = assignments
                .Where(a => a.Id == SearchId)
                .Include(a => a.Teacher)
                .Include(a => a.Subject);
            return View(await assignments.ToListAsync());

        }


        // GET: Assignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .Include(a => a.Subject)
                .Include(a => a.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // GET: Assignments/Create
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id");
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id");
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TeacherId,SubjectId")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", assignment.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", assignment.TeacherId);
            return View(assignment);
        }

        // GET: Assignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", assignment.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", assignment.TeacherId);
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TeacherId,SubjectId")] Assignment assignment)
        {
            if (id != assignment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentExists(assignment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", assignment.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", assignment.TeacherId);
            return View(assignment);
        }

        // GET: Assignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .Include(a => a.Subject)
                .Include(a => a.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Assignments == null)
            {
                return Problem("Entity set 'PdpDbContext.Assignments'  is null.");
            }
            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment != null)
            {
                _context.Assignments.Remove(assignment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssignmentExists(int id)
        {
            return (_context.Assignments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Lesson03/Views/Assignments/Create.cshtml
@model Lesson03.Models.Assignment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <select asp-for="TeacherId" class ="form-control" asp-items="ViewBag.TeacherId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lesson03/Views/Assignments/Delete.cshtml
@model Lesson03.Models.Assignment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lesson03/Views/Assignments/Details.cshtml
@model Lesson03.Models.Assignment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lesson03/Views/Assignments/Edit.cshtml
@model Lesson03.Models.Assignment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <select asp-for="TeacherId" class="form-control" asp-items="ViewBag.TeacherId"></select>
                <span asp-validation-for="TeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lesson03/Views/Assignments/Index.cshtml
@model IEnumerable<Lesson03.Models.Assignment>

@{
    ViewData["Title"] = "Index";
}

<h1>Assignments</h1>
<form asp-controller="Assignments" asp-action="Index" >
    <p>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="27" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg>
                </span>
            </div>
             <input type="number" class="form-control" placeholder="Search by Id" name="SearchId" />
             <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit" >
                 <i class="fas fa-search"></i> Search
                </button>
             </div>
        </div>
    </p>
</form>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model=>model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem=>item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject.Id)
            </td>
                <td>
                    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
        </tr>
}
    </tbody>
</table>